### PR TITLE
Add i18n support and zh_CN translate

### PR DESCRIPTION
**Pull request by zetako**
This MR add i18n related scripts from [Zren/plasma-applet-lib](https://github.com/Zren/plasma-applet-lib/tree/master/package/translate), with some tweaks. I am totally new to KDE community, so I can't comfirm those changes are correct.

- Delete everything related to `.Desktop` file since we don't have it.

### How to

- Use `merge` to generate a new template if components got changed; ignore it if you just want to translate.
- Copy `template.pot` as your translation file, like `zh_CN.po`.
- Implement all `msgstr` part.
- Use `build` to generate translations form plaintext `.po` file.
- You need to execute scripts within `translate` dir.

### Others

I also add a zh_CN translation as an example.

### CODE REVIEW

**Comment by alexankitty** [comment]
Sorry I've been away from this for a while. Maintaining the project was super stressful and I've just not had access to a linux install as my daily driver. Can you catch me up to speed on what exactly I need to do on my end before I merge this?

**Comment by zetako** [comment]
Welcome back and thanks for your awesome project.

> Can you catch me up to speed on what exactly I need to do on my end before I merge this?

### Basic

I found this script in other plasma plugin and the original author seems to be the KDE developer. Check this [link](https://github.com/Zren/plasma-applet-lib/tree/master/package/translate). 

It work like this:
1. Developer of plugin wrap string needed i18n using `i18n()` (Already done in your code)
2. Generate a template using `merge` script
3. Translators implement their `.po` file as translate
4. Use `build` to generate `.mo` file as i18n asset, the readme file showing translate progress will also updated
5. Put `.mo` file in `content/locale`, the KDE framework will automatically use it

### The Submit

I do some change on the script.
- The original one will read `.desktop` file for plugin infos like name and website, and we dont have this file, so I simply just manully implement these infos
- The original one will try to i18n `.desktop` file, I just delete them

There's still a problem with the submit, that I added the generated `.mo` file. It's a binary file so it can cause security issue and also diffcult to manage during version changing. I think we should only accept and store the `.po` file and generate `.mo` files everytime a new release is packaged.

**Comment by alexankitty** [comment]
Yeah I think that's a good idea. I'll add it to my list to implement build-time translations so that double duty isn't required to manage translations. Though you'll have to forgive me on this one, since it's not something I've implemented before.

**Comment by alexankitty** [comment]
This looks to be for an older version of Plasmoids using a metadata.desktop file. They use JSON now for this. I'll need to research the implementation of this further.

**Comment by alexankitty** [comment]
Manually merged in, feel free to update zh_CN.po as needed.

**Pull request closed without merging**
